version: '2'
services:
  jvm-bloggers-db:
    image: sameersbn/postgresql:9.4-22
    environment:
      DB_USER: $JVM_BLOGGERS_DB_USER
      DB_PASS: $JVM_BLOGGERS_DB_PASSWORD
      DB_NAME: $JVM_BLOGGERS_DB_NAME
    ports:
      - "$JVM_BLOGGERS_DB_PUBLISHED_PORT:5432"
    volumes:
      - "$JVM_BLOGGERS_DB_PATH:/var/lib/postgresql"
  jvm-bloggers-core:
    image: jvmbloggers/jvm-bloggers:$JVM_BLOGGERS_CORE_IMAGE_VERSION
    environment:
      spring.profiles.active: $JVM_BLOGGERS_CORE_SPRING_PROFILES
      jasypt.encryptor.password: $JVM_BLOGGERS_CORE_ENCRYPTOR_PASSWORD
    ports:
      - "$JVM_BLOGGERS_CORE_PORT:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo/Europe/Warsaw:/etc/timezone:ro
      - /tmp
    links:
      - jvm-bloggers-db
    depends_on:
      - jvm-bloggers-db
