info:
  app:
    name: JVM Bloggers
    description: Application to spread info about polish blogging JVM Developers

spring:
  http.encoding.force: true
  mandatory-file-encoding: UTF-8 
  jpa.hibernate.ddl-auto: validate
liquibase.change-log: classpath:db/changelog/db.changelog.xml

spring-data-releasetrain.version: Ingalls-SR1

server.compression:
  enabled: true
  mime-types: application/atom+xml,text/html,text/xml,text/plain,text/css,text/javascript,application/javascript
 
bloggers.data.file.url: https://raw.githubusercontent.com/jvm-bloggers/jvm-bloggers/master/src/main/resources/blogs/bloggers.json
companies.data.file.url: https://raw.githubusercontent.com/jvm-bloggers/jvm-bloggers/master/src/main/resources/blogs/companies.json
youtube.data.file.url: https://raw.githubusercontent.com/jvm-bloggers/jvm-bloggers/master/src/main/resources/blogs/videos.json
generated.rss.entries.limit: 50
items.pagination.size: 15
max.new.post.age.days: 30
cache.spec: expireAfterWrite=1d

application.baseUrl: http://jvm-bloggers.com
application.issueUrl: ${application.baseUrl}/issue/

# Logging
logging.level.root: INFO
logging.level.com.jvm_bloggers: INFO

scheduler.fetch-bloggers-data: 0 0 7,9,11,13,15,17,19,21,23 * * *
scheduler.fetch-rss-for-new-blogs: 0 30 * * * *
scheduler.publish-new-issue: 0 0 13 * * FRI
scheduler.send-email: 240000 # 4 minutes

github.api:
  token: #Personal access tokens can be created under https://github.com/settings/tokens
  apiUrl: https://api.github.com
  org: jvm-bloggers
  repo: jvm-bloggers
